local _, T = ...

T.KnownSpells = {
	[90]={phase=0, type="passive", target="friend-surround", modDamageDealt=20},
	[53]={type="aura", target="all-enemies", duration=6, period=2, modDamageDealt=-20, damageATK=0.1},
	[89]={type="aura", target=1, duration=3, damageATK=0.4},
	[96]={type="nuke", target=1, duration=2, damageATK=0.4, modDamageDealt=-20},
	[138]={type="nuke", target="cleave", pretarget=0, damageATK=0.3},
	[200]={type="aura", target=0, damageATK=1, modDamageDealt=-50, duration=1},
	[143]={type="aura", target=4, modDamageDealt=25, duration=2, fadeOrd=-100},
	[144]={type="aura", target="all-other-allies", modDamageTaken=-75, duration=2, firstTurn=4},
	[71]={type="heal", target=3, healATK=1},
	[7]={type="nuke", target=0, damageATK=0.1},
	[12]={type="heal", target="all-allies", healATK=0.2},
	[246]={type="nuke", target=0, damageATK=1.5},
	[247]={type="nuke", target=0, damageATK=0.1, healATK=0.2, healTarget="self", firstTurn=4},
	[258]={type="aura", target=0, damageATK=0.5, damageATK1=1, duration=1, echo=3},
	[97]={type="nuke", target="cone", pretarget=0, damageATK=0.9},
	[248]={type="aura", target=0, damageATK=0.15, damageATK1=0.3, duration=5, noFirstTick=true},
	[43]={type="nuke", target=1, damageATK=0.25, healATK=0.2, healTarget="self"},
	[169]={type="aura", target=0, damageATK=0.5, damageATK1=0.65, duration=1, echo=3},
	[159]={type="aura", target="all-enemies", modDamageDealt=-25, duration=2},
	[9]={type="heal", target="all-allies", healPercent=5 },
	[19]={type="nuke", target=0, damageATK=1.5},
	[135]={type="nuke", target="row", pretarget=5, damageATK=3},
	[4]={type="nuke", target=0, damageATK=0.75, damageATK2=0.5 },
	[44]={type="nuke", target=0, damageATK=0.5, damageATK2=0.25 },
	[48]={type="heal", target=4, healATK=0.2, shroudTurns=1},
	[21]={type="aura", target="all-allies", healATK=0.15, duration=5, noFirstTick=true},
	[45]={type="nuke", target=1, damageATK=0.75, healATK=0.25, healTarget="self"},
	[6]={type="nuke", target="row", pretarget=5, damageATK=0.5},
	[49]={type="aura", target="row", pretarget=5, modDamageTaken=33, duration=4},
	[54]={
		{type="nuke", target=0, damageATK=0.45},
		{type="nuke", target=1, damageATK=0.45}
	},
	[61]={type="nuke", target=0, damageATK=0.75},
	[60]={type="nuke", target=1, damageATK=0.4},
	[103]={type="aura", target="all-other-allies", modDamageDealt=100, duration=2},
	[104]={
		{type="heal", target=3, healATK=1},
		{type="aura", target=3, modDamageDealt=-10, duration=1},
	},
	[117]={type="nuke", target="row", pretarget=6, damageATK=0.4},
	[118]={type="nuke", target=1, damageATK=2, firstTurn=4},
	[168]={type="aura", target=0, modDamageDealt=-50, duration=2},
	[145]={type="nuke", target=0, damageATK=0.75},
	[146]={type="nuke", target=1, damageATK=0.75},
	[185]={type="nuke", target="all-enemies", damageATK=1},
	[249]={type="aura", target=0, damageATK1=0.6, duration=1, modDamageDealt=-50},
	[126]={type="heal", target="row", pretarget=10, healATK=0.2, selfAvoid=true},
	[250]={type="nuke", target=1, damageATK=0.8, firstTurn=4, },
	[286]={type="aura", target=3, modDamageDealt=50, duration=2},
	[287]={type="aura", target=4, modDamageTaken=-50, duration=1},
	[202]={type="taunt", target="all-enemies", duration=2},
	[203]={type="nuke", target="row", pretarget=6, damageATK=1 },
	[165]={type="nuke", target=0, damageATK=3},
	[164]={type="nuke", target="cone", pretarget=0, damageATK=2, echo=3},
	[66]={type="nuke", target=0, damageATK=1.5},

	[262]={type="nuke", target="row", pretarget=6, damageATK=1 },
	[263]={type="nuke", target="cone", pretarget=0, damageATK=1 },
	[261]={type="aura", target=3, modDamageDealt=50, duration=2},
	[10]={
		{type="nuke", target=0, damagePerc=20},
		{type="aura", target="all-enemies", duration=4, damagePerc=3, noFirstTick=true},
		{type="aura", target=4, healPerc=1, duration=4, noFirstTick=true},
	},
	[119]={type="nuke", target="cone", pretarget=0, damageATK=1},
	[64]={type="nuke", target="all-enemies", damageATK=1.5 },
	[217]={type="nuke", target="row", pretarget=5, damageATK=2 },
	[201]={type="nuke", target="row", pretarget=5, damageATK=2 },
	[116]={type="nuke", target=0, damageATK=1.2},
	[63]={type="aura", target="all-enemies", modDamageDealt=-20, duration=2, damageATK1=0.6 },
	[204]={type="aura", target=0, damageATK1=1.5, modDamageDealt=-50, duration=2},
	[231]={
		{type="fork", target="all-enemies"},
		{type="aura", target="fork", modDamageTaken=100, duration=2}
	},
	[224]={type="nuke", target="row", pretarget=6, damageATK=0.5},
	[226]={type="nuke", target="cone", pretarget=0, damageATK=0.5},
	[46]={
		{type="aura", target=4, modDamageTaken=-10, duration=1},
		{type="aura", target="row-other", pretarget=7, modDamageTaken=-10, duration=1},
	},
	[50]={type="nuke", target=1, damageATK=1.2},
	[51]={type="nuke", target="row", pretarget=6, damageATK=0.75},
	[52]={type="nuke", target="row", pretarget=5, damageATK=0.3},

	[87]={type="nuke", target="row", pretarget=5, damageATK=0.6},
	[88]={
		{type="aura", target=4, modDamageDealt=30, duration=3},
		{type="nuke", target="all-enemies", damageATK=0.4}
	},
	[299]={type="nuke", target=1, damageATK=2},
	[193]={
		{type="nuke", target="row", pretarget=6, damageATK=3},
		{type="nuke", target=4, damageATK=0.5}
	},
	[113]={type="nuke", target="cone", pretarget=0, damageATK=1.2 },
	[111]={type="nuke", target="row", pretarget=6, damageATK=1 },
	[112]={type="aura", target="friend-surround", duration=3, plusDamageDealtATK=0.3},
	[107]={
		{type="aura", target="all-enemies", damageATK=0.4, duration=4},
		{type="aura", target=0, plusDamageTakenATK=0.3, duration=3},
	},
	[108]={
		{type="heal", target=3, healATK=0.4},
		{type="aura", target=3, modMaxHP=10, duration=2},
	},
	[274]={type="nuke", target="row", pretarget=6, damageATK=1.2},
	[211]={type="nuke", target="cone", pretarget=0, damageATK=1.5 },
	[281]={type="nuke", target=1, damageATK=1.5 },
	[82]={type="passive", target=4, thornsATK=0.25},
	[83]={type="nuke", target="cleave", pretarget=0, damageATK=1.2 },
	[75]={type="nuke", target=1, damageATK=1},
	[147]={type="aura", target="all-other-allies", modDamageTaken=-50, duration=2, },
	[275]={type="aura", target=3, modDamageDealt=75, duration=2, },
	[276]={type="aura", target=1, duration=1, damageATK1=0.25, damageATK=0.5, echo=3},
	[25]={
		{type="nuke", target="row", pretarget=6, damageATK=0.5, },
		{type="aura", target=4, modDamageDealt=20, duration=3, }
	},
	[290]={type="nuke", target=1, damageATK=1.5},
	[291]={type="nuke", target="row", pretarget=6, damageATK=1},
	[186]={type="nuke", target="row", pretarget=6, firstTurn=5, damageATK=2},
	[94]={type="aura", target="row", pretarget=6, duration=4, damageATK=0.3, noFirstTick=true},
	
	[11]={type="nuke", target=0, damageATK=1},
	[15]={type="nuke", target=1, damageATK=1},
	[244]={firstTurn=2,
		{type="aura", target=4, plusDamageDealtATK=2, plusDamageTakenATK=0.3, duration=2},
		{type="nuke", target=0, damageATK=0.3},
	},
	[22]={type="aura", target="cleave", pretarget=0, duration=3, damageATK=0.1, damageATK1=0.5, noFirstTick=true},
	[124]={type="nuke", target="cleave", pretarget=0, damageATK=0.6},
	[120]={
		{type="fork", target="all-enemies"},
		{type="aura", target="fork", modDamageDealt=50, duration=2},
	},
	[260]={type="nuke", target=1, damageATK=1.5},
	[259]={type="aura", target=0, duration=0, echo=3, noFirstTick=true, damageATK=0.3},
	[255]={type="aura", target=3, modDamageTaken=-50, duration=1, },
	[256]={type="nuke", target="cone", pretarget=0, damageATK=1 },
	[121]={type="aura", target="all-enemies", modDamageDealt=-50, duration=1, },
	[122]={type="nop"},
	[123]={type="heal", target="row", pretarget=10, healATK=0.3, selfAvoid=true},
	[172]={type="aura", target="row", pretarget=6, firstTurn=3, duration=1, modDamageDealt=-50, damageATK1=0.2 },
	[173]={type="aura", target=1, modDamageDealt=-25, duration=2, damageATK1=0.75 },
	[130]={type="aura", target=4, duration=3, thornsATK=1},
	[288]={type="nuke", target="row", pretarget=5, damageATK=0.6},
	[294]={type="nuke", target=0, damageATK=2},
	[187]={type="nuke", target="all-enemies", echo=2, damageATK=0.5},
	[156]={type="aura", target="all-enemies", modDamageTaken=40, duration=2, },
	[158]={type="nuke", target="row", pretarget=5, firstTurn=3, damageATK=3},
	[154]={type="aura", target=4, duration=3, thornsATK=1},
	[153]={type="nuke", target="cone", pretarget=0, damageATK=0.75},
	[157]={type="nuke", target="cleave", pretarget=0, damageATK=0.8 },
	[205]={type="heal", target="row", pretarget=10, healATK=0.75, selfAvoid=true},
	[206]={type="nuke", target=0, damageATK=1.5 },
	[208]={type="nop"


	},
	[209]={
		{type="fork", target="all-allies"},
		{type="aura", target="fork", modDamageDealt=50, duration=1},
	},
	[272]={type="nuke", target=1, damageATK=1.5},
	[170]={type="nuke", target="row", pretarget=6, damageATK=0.6},
	[171]={type="nuke", target=1, damageATK=1, },
	[266]={type="nuke", target=0, damageATK=10},
	[136]={type="aura", target=0, duration=0, damageATK=1.5, noFirstTick=true, echo=3},
	[292]={
		{type="aura", target=0, modDamageTaken=50, duration=2},
		{type="nuke", target=0, damageATK=0.75},
	},
	[160]={type="nuke", target="all-enemies", damageATK=2, },
	[218]={type="aura", target=4, duration=2, modDamageTaken=-50, },
	[174]={type="aura", target=4, duration=3, thornsATK=0.4, },
	[176]={type="aura", target="all-enemies", duration=1, modDamageTaken=25, },
	[177]={type="nuke", target=0, damageATK=0.5, },
	[225]={type="nuke", target="cone", pretarget=0, damageATK=0.5, },
	[24]={
		{type="nuke", target=1, damageATK=1.5, },
		{type="heal", target=3, healATK=0.2, },
	},
	[127]={type="nuke", target="row", pretarget=6, damageATK=0.6, },
	[128]={type="nuke", target="row", pretarget=5, damageATK=0.75, },
	[283]={type="nuke", target=0, damageATK=0.75},
	[284]={type="aura", target="all-other-allies", duration=1, modDamageTaken=-50, },
	[296]={type="nuke", target="row", pretarget=5, damageATK=1, firstTurn=3},
	[99]={type="nuke", target="row", pretarget=6, damageATK=1.4, },
	[166]={
		{type="fork", target="all-allies"},
		{type="nuke", target="fork", damageATK=1, },
		{type="heal", target=4, healATK=0.5, },
	},
	[167]={type="nuke", target=1, damageATK=1.5, },
	[175]={
		{type="fork", target="all"},
		{type="nuke", target="fork", damageATK=1.2, }
	},
	[282]={type="nuke", target=0, damageATK=10, firstTurn=5},
	[55]={type="nuke", target="row", pretarget=6, damageATK=0.3, },
	[150]={type="nuke", target="cone", pretarget=0, damageATK=0.5, },
	[155]={type="aura", target="all-enemies", duration=1, modDamageDealt=-75, },
	[280]={type="nuke", target="row", pretarget=6, damageATK=2.5, },
	[252]={
		{type="nuke", target="cleave", pretarget=0, damageATK=0.6, },
		{type="aura", target="cleave", pretarget=0, duration=2, modDamageTaken=25, },
	},
	[253]={type="nuke", target="row", pretarget=6, damageATK=0.75, },
	[254]={type="aura", target="all-other-allies", firstTurn=3, duration=3, thornsATK=1, },
	[125]={
		{type="fork", target="all-enemies"},
		{type="nuke", target="fork", damageATK=0.6, },
	},
	[219]={
		{type="heal", target=3, healATK=2, },
		{type="aura", target=3, duration=2, modDamageTaken=-50, },
	},
	[220]={type="nuke", target="row", pretarget=6, damageATK=1, },
	[114]={type="heal", target=4, healATK=1},
	[267]={type="nuke", target=1, damageATK=1.5, },
	[268]={type="aura", target="row", pretarget=6, duration=3, modDamageDealt=-30, },
}